<?php

use PHPUnit\Framework\TestCase;
use App\OrderStatus;

class OrderTest extends TestCase
{
    public function testStatusOfOrderNumber()
    {
        $order_id = 'ORD0005134';

        $order_status = OrderStatus::getCurrentOrderStatus($order_id);

        $this->assertEquals('OPEN', $order_status);
    }

    public function testChangeStatusToPending()
    {
        $order_id = 'ORD0008866';

        OrderStatus::updateCurrentOrderStatus($order_id, 'PENDING');

        $order_status = OrderStatus::getCurrentOrderStatus($order_id);

        $this->assertEquals('PENDING', $order_status);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $order_id = 'ORD0008866';

        OrderStatus::updateCurrentOrderStatus($order_id, 'OPEN');
    }
}